# Default values for kvm-manager.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

auth:
  ssh_key: FILL-ME-IN
  
images:
  entrypoint: quay.io/attcomdev/kvm-manager:latest
  kvm_manager: quay.io/attcomdev/kvm-manager:latest

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

volume:
  class_path: volume.beta.kubernetes.io/storage-class
  class_name: general
  size: 25Gi

network:
  port: 22
  vnc: 5900
