sudo: required

matrix:
  include:
    - language: go
      go: 
        - 1.9

    - language: bash
      services:
        - docker
      script:
        - docker build -t vect0r/fluentd_exporter .
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
          docker push vect0r/fluentd_exporter;
          fi

notifications:
  email:
    - "$EMAIL"
