apiVersion: v1
kind: Service
metadata:
  name: maas-region-ui
spec:
  selector:
    app: maas-region
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: gui
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: proxy
